/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class com_onlylemi_jnitest_MainActivity */

#ifndef _Included_com_onlylemi_jnitest_MainActivity
#define _Included_com_onlylemi_jnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

char* cs;

/*
 * Class:     com_onlylemi_jnitest_MainActivity
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onlylemi_jnitest_MainActivity_get(JNIEnv *, jobject);

/*
 * Class:     com_onlylemi_jnitest_MainActivity
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onlylemi_jnitest_MainActivity_set(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
